### ISSUE TITLE
MyGrad 2.0 Todo

### ISSUE THREAD

**Issue by rsokl** [rsokl/MyGrad#336]
- [x] Implement `tensor` function so that `tensor(t, copy=False)` can return `t`
- [x] Remove / document scalar-only backprop checks
- [x] Support `dtype`, `where`, and `out` across ufuncs
- [x] Make `constant` keyword-only and set default to `None`
- [x] Add basic, but incisive type annotations
- [x] ~Special case binary ufuncs on identical inputs~
- [x] Design wrapper for exposing ufuncs, without disfiguring docs
- [x] Add dtype aliases
- [x] Don't monkey patch methods onto Tensor
- [ ] Look into setting [default role](https://www.sphinx-doc.org/en/master/usage/restructuredtext/roles.html) in sphinx
- [x] ~Make ufunc attributes class attributes~
- [x] Add `copy` options to `Tensor.astype`
